config/routes.rb
NewGmd::Application.routes.draw do

  devise_for :users
  resources :tasks do
    resources :problems, only: [:update, :edit, :destroy]
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true

	mount_uploader :name, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper

	def number_alerts
		Task.joins(:material).where('tasks.updated_at < ? and materials.in_deposito = ?', 
			Time.now.at_beginning_of_day - 3.days, false).count
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NewGmd" %></title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8f6X06N2yN7Wxn3f7e-hkThvcubz9vFc&sensor=true">
    </script>

    <%= yield(:css) %>
  </head>
  <body>

    <%= nav_bar :fixed => :top, :brand => "GMD", :brand_link => root_path, :responsive => true do %>
      <% if user_signed_in? %>
        <%= menu_group do %>
          <%= drop_down "Cadastros" do %>
            <%= menu_item "Empresas", companies_path  %>
            <%= menu_item "Pessoas", pessoas_path  %>
            <%= menu_item "Contâiners", materials_path  %>
            <%= menu_item "Localização do Contâiner", container_locations_path  %>
            <%= menu_item "Caminhões", trucks_path  %>
            <%= menu_item "Tipo de Entulhos", entulhos_path  %>
          <%end%>
          <%= menu_item "Tarefas", tasks_path %>
        <% end %>
        <%= menu_group :pull => :right do %>
          <%= menu_item alerts_path do %>
            Alertas 
            <span class="badge badge-important">
              <%= number_alerts %>
            </span>
          <% end %>
          <%= drop_down current_user.email do %>
            <%= menu_item "Sair", destroy_user_session_path, :method => :delete  %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <%= nav_bar :fixed => :bottom, :responsive => true do %>
        <footer>
          <p>&copy; Digitus 2014. by Roga Labs</p>
        </footer>
      <%end%>

    </div> <!-- /container -->
    <%= javascript_include_tag "application" %>
  </body>
</html>